export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const GET_FILTER_PRODUCTS = "GET_FILTER_PRODUCTS";
export const GET_FILTER_PRODUCTS_SUCCESS = "GET_FILTER_PRODUCTS_SUCCESS";

export const GET_FIND_PRODUCT = "GET_FIND_PRODUCT";
export const GET_FIND_PRODUCT_SUCCESS = "GET_FIND_PRODUCT_SUCCESS";

export const POST_PRODUCT = "POST_PRODUCT";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const REMOVE_STOCK = "REMOVE_STOCK";
export const REMOVE_STOCK_SUCCESS = "REMOVE_STOCK_SUCCESS";

export const GET_HISTORIAL= "GET_HISTORIAL";
export const GET_HISTORIAL_SUCCESS= "GET_HISTORIAL_SUCCESS";

export const FIND_DELETED= "FIND_DELETED";
export const FIND_DELETED_SUCCESS= "FIND_DELETED_SUCCESS";

export const FIND_DELETED_BYDATE= "FIND_DELETED_BYDATE";
export const FIND_DELETED_BYDATE_SUCCESS= "FIND_DELETED_BYDATE_SUCCESS";

export const ADD_STOCK= "ADD_STOCK";
export const ADD_STOCK_SUCCESS= "ADD_STOCK_SUCCESS";

export const GET_HISTORIAL_ENTRADAS= "GET_HISTORIAL_ENTRADAS";
export const GET_HISTORIAL_ENTRADAS_SUCCESS= "GET_HISTORIAL_ENTRADAS_SUCCESS";

export const FIND_ENTRADAS= "FIND_ENTRADAS";
export const FIND_ENTRADAS_SUCCESS= "FIND_ENTRADAS_SUCCESS";

export const FIND_ENTRADAS_BYDATE= "FIND_ENTRADAS_BYDATE";
export const FIND_ENTRADAS_BYDATE_SUCCESS= "FIND_ENTRADAS_BYDATE_SUCCESS";
