export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const GET_FILTER_PRODUCTS = "GET_FILTER_PRODUCTS";
export const GET_FILTER_PRODUCTS_SUCCESS = "GET_FILTER_PRODUCTS_SUCCESS";

export const GET_FIND_PRODUCT = "GET_FIND_PRODUCT";
export const GET_FIND_PRODUCT_SUCCESS = "GET_FIND_PRODUCT_SUCCESS";

export const POST_PRODUCT = "POST_PRODUCT";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const REMOVE_STOCK = "REMOVE_STOCK";
export const REMOVE_STOCK_SUCCESS = "REMOVE_STOCK_SUCCESS";

export const GET_HISTORIAL= "GET_HISTORIAL";
export const GET_HISTORIAL_SUCCESS= "GET_HISTORIAL_SUCCESS";
