export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const GET_FILTER_PRODUCTS = "GET_FILTER_PRODUCTS";
export const GET_FILTER_PRODUCTS_SUCCESS = "GET_FILTER_PRODUCTS_SUCCESS";

export const GET_FIND_PRODUCT = "GET_FIND_PRODUCT";
export const GET_FIND_PRODUCT_SUCCESS = "GET_FIND_PRODUCT_SUCCESS";

export const POST_PRODUCT = "POST_PRODUCT";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
